[package]
name = "znp-rs"
version = "0.1.0"
authors = ["qm3ster <qm3ster@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.12"
futures-preview = "0.3.0-alpha.13"
num-derive = "0.2.4"
num-traits = "0.2.6"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0.39"
serde_repr = "0.1.3"
tokio = { version = "0.1.18", features = ["async-await-preview"] }
tokio-serial = "3.2.0"
